CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE superman WITH LOGIN PASSWORD 'superman' NOCREATEROLE NOSUPERUSER INHERIT NOCREATEDB NOREPLICATION;
CREATE DATABASE heroes_database;
GRANT ALL PRIVILEGES ON DATABASE heroes_database TO superman ;
GRANT ALL PRIVILEGES ON DATABASE heroes_database TO super;

CREATE ROLE superbad WITH LOGIN PASSWORD 'superbad' NOCREATEROLE NOSUPERUSER INHERIT NOCREATEDB NOREPLICATION;
CREATE DATABASE villains_database;
GRANT ALL PRIVILEGES ON DATABASE villains_database TO superbad;
GRANT ALL PRIVILEGES ON DATABASE villains_database TO super;

CREATE ROLE superfight WITH LOGIN PASSWORD 'superfight' NOCREATEROLE NOSUPERUSER INHERIT NOCREATEDB NOREPLICATION;
CREATE DATABASE fights_database;
GRANT ALL PRIVILEGES ON DATABASE fights_database TO superfight;
GRANT ALL PRIVILEGES ON DATABASE fights_database TO super;

